spring.application.name=backend-liveAuction
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=eslamelkasabi
spring.datasource.password=

# Hibernate/JPA Configuration
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true