spring.application.name=backend-liveAuction
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=eslamelkasabi
spring.datasource.password=

# Hibernate/JPA Configuration
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
# 1. The Secret Key (Make sure it is long! At least 32 characters)
jwt.secret=my_super_secret_key_for_the_live_auction_app_that_is_long_enough
# 2. Expiration Time in Milliseconds (86400000 ms = 24 hours)
jwt.expirationMs=86400000